# Generated by Django 5.0.4 on 2024-05-16 00:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tipo_cotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('peso_minimo', models.IntegerField()),
                ('peso_maximo', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='tipo_entrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='unidad_medida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('abreviacion', models.CharField(max_length=10)),
                ('multiplo', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='solicitud_cotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(max_length=100)),
                ('contacto', models.TextField(blank=True)),
                ('direccion_entrega', models.TextField(blank=True)),
                ('tipo_cotizacion_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='price.tipo_cotizacion')),
                ('tipo_entrega_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='price.tipo_entrega')),
            ],
        ),
        migrations.CreateModel(
            name='cotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('venta', models.BooleanField(default=False)),
                ('usuario_id', models.TextField(max_length=100)),
                ('solicitud_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='price.solicitud_cotizacion')),
                ('unidad_medida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='price.unidad_medida')),
            ],
        ),
    ]
