# Generated by Django 5.0.4 on 2024-05-16 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud_cotizacion',
            name='producto',
            field=models.TextField(blank=True),
        ),
    ]
