# Generated by Django 5.0.4 on 2024-05-16 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0002_solicitud_cotizacion_producto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipo_cotizacion',
            name='deleted_at',
            field=models.DateTimeField(default='null', null=True),
        ),
        migrations.AlterField(
            model_name='tipo_entrega',
            name='deleted_at',
            field=models.DateTimeField(default='null', null=True),
        ),
    ]
