# Generated by Django 5.0.4 on 2024-05-22 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0007_alter_solicitud_cotizacion_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud_cotizacion',
            name='cantidad',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
    ]
