# Generated by Django 5.0.4 on 2024-05-22 02:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0008_solicitud_cotizacion_cantidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud_cotizacion',
            name='unidad_medida',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='price.unidad_medida'),
            preserve_default=False,
        ),
    ]
