# Generated by Django 5.0.4 on 2024-05-29 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0009_solicitud_cotizacion_unidad_medida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud_cotizacion',
            name='estado',
            field=models.BooleanField(default=False),
        ),
    ]
